#!/usr/bin/env python3
"""
Memory Parser - Convert memories.json to tagged JSONL
=====================================================

Converts your ChatGPT memories export to a tagged JSONL format.
Tags are automatically applied based on patterns discovered by analyze_patterns.py.

Configuration:
  Reads keywords from memory/patterns.jsonl (generated by analyze_patterns.py)
  Works without config - just outputs untagged records.

Usage:
  python parse_memories.py                  # Use default paths
  python parse_memories.py --input mem.json # Custom input file

Input format (memories.json):
  {
    "memories": [
      {"id": "...", "content": "...", "updated_at": "..."},
      ...
    ]
  }

Output format (user.context.jsonl):
  {"id": "...", "type": "user.context", "content": "...", "tags": [...]}
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from memory_parser_common import (
    USER_ID,
    extract_tags,
    get_user_dir,
    load_keywords,
)

SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Parse memories.json to tagged JSONL",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--input", type=str, default=None, help="Path to memories.json")
    parser.add_argument("--output", type=str, default=None, help="Path for output JSONL")
    args = parser.parse_args()

    memory_dir = get_user_dir(PROJECT_ROOT / "memory", USER_ID)

    memories_path = Path(args.input) if args.input else memory_dir / "memories.json"
    output_path = Path(args.output) if args.output else memory_dir / "user.context.jsonl"
    patterns_path = memory_dir / "patterns.jsonl"

    if not memories_path.exists():
        print(f"Error: memories.json not found at {memories_path}")
        sys.exit(1)

    keywords = load_keywords(patterns_path)
    if keywords:
        print(f"Loaded {len(keywords)} keywords from patterns.jsonl")
    else:
        print("No patterns.jsonl found - memories will have basic tags")
        print("  Tip: Run 'python analyze_patterns.py' first for auto-tagging")

    with open(memories_path, encoding="utf-8") as f:
        data = json.load(f)

    if "memories" not in data or not isinstance(data["memories"], list):
        print("Error: Invalid memories.json format")
        print('Expected: {"memories": [{"id": ..., "content": ...}, ...]}')
        sys.exit(1)

    output_lines = []
    tag_counts: dict[str, int] = {}

    for memory in data["memories"]:
        content = memory.get("content", "")
        tags = extract_tags(content, keywords)

        for tag in tags:
            tag_counts[tag] = tag_counts.get(tag, 0) + 1

        record = {
            "id": f'user-context-{memory["id"]}',
            "type": "user.context",
            "content": content,
            "source": "chatgpt_memories",
            "source_id": memory["id"],
            "updated_at": memory.get("updated_at"),
            "createdAt": memory.get("updated_at"),
            "tags": tags,
        }
        output_lines.append(json.dumps(record, ensure_ascii=False))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(output_lines) + ("\n" if output_lines else ""))

    print(f"\n✅ Parsed {len(data['memories'])} memories to {output_path}")

    if tag_counts:
        print("\nTop tags applied:")
        for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1])[:10]:
            print(f"  {tag}: {count}")


if __name__ == "__main__":
    main()
